sonar.projectKey=Barret-Pierre_Score-It
sonar.organization=barret-pierre

sonar.projectName=score-it
sonar.projectVersion=0.2.1

sonar.sources=src
sonar.tests=tests
sonar.exclusions=node_modules/**,coverage/**,.expo/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/*.types.ts,src/domain/models/**,**/*.d.ts,**/*.styles.ts
